Add tag bottom sheet (Create Screen and Done Screen)
vamelchenia/nerd-translator pull request #20
Opened 2023-10-19 11:52 UTC by LexaNik

https://github.com/vamelchenia/nerd-translator/assets/145274573/33f72a22-36d7-4107-be88-89d70ee7d17c

2023-10-19 12:08 UTC, Steyrix requested changes
Need fix

2023-10-19 12:08 UTC, Steyrix commented on app/src/main/java/com/llcompany/nerdtranslator/base/main/ui/composables/NerdTranslatorAppBar.kt
> +//            ActionButtonBackSheet {
В коде, который пушим, не оставляем закоментированные куски кода

2023-10-19 12:08 UTC, Steyrix commented on app/favourites_screen/src/main/java/com/example/favouritesscreen/composables/FavouritesScreen.kt
> +                if ((createTagSheetViewModelState.isValid)
Лучше это сложное условие вынести в отдельную переменную

2023-10-19 12:08 UTC, Steyrix commented on app/favourites_screen/src/main/java/com/example/favouritesscreen/composables/FavouritesScreen.kt
> +    Scaffold(
Вот в чем проблема, здесь ты создаешь отдельный `Scaffold`, хотя он у нас уже есть в NavigationHolder'e.
Новый скаффолд рисуется поверх другого и соответственно под боттомшитом ничего не видно. Тебе нужно с помощью эффектов и ивентов отследить момент, когда нужно показать bottomSheet и делегировать это поведение в NavigationHolder. Определить показ и условие боттомшита нужно там, потом можно передать это с помощью лямбд в `FavouritesScreenDestination`, например.

2023-10-19 12:08 UTC, Steyrix commented on app/favourites_screen/src/main/java/com/example/favouritesscreen/composables/FavouritesScreen.kt
> +                val createTagSheetViewModelState = createTagSheetViewModel.getState().value
Ну и состояние/условие отвечающее за то, показывать ли боттомшит не относится к `createTagSheetViewModelState`. Эту вьюмодель вообще нельзя и нежелательно использовать в этом композабле. 
Она и ее состояние не должны знать о том, что происходит за их пределами. Показываются они или нет - не их дело )

2023-10-19 12:08 UTC, Steyrix commented on app/create_tag_sheet/src/main/java/com/example/createtagsheet/composables/CreatedTagLabel.kt
> +//        Box(
Закоментированный код не оставляем в коммитах

2023-10-19 12:08 UTC, Steyrix commented on app/create_tag_sheet/src/main/java/com/example/createtagsheet/composables/CreateTagInput.kt
> +private val borderColor = Color(0xFFF2575D)
Везде, где ты определяешь цвета, нужно убедиться, что их нет в нашей theme

2023-10-19 12:08 UTC, Steyrix commented on app/create_tag_sheet/src/main/java/com/example/createtagsheet/composables/CreateTagInput.kt
> +private val borderColor = Color(0xFFF2575D)
Если их нет - то можно определить в сыром виде, если есть - нужно использовать значения из темы

2023-10-19 12:12 UTC, Steyrix commented
Вообще всю логику показа боттомшита нужно переписать и разместить ее в NavigationHolder'е.

Нужно настроить "общение" между ним и экраном тегов. Делается это с помощью лямбд и эффектов

2023-10-21 19:15 UTC, LexaNik commented on app/create_tag_sheet/src/main/java/com/example/createtagsheet/composables/CreateTagInput.kt
> +private val borderColor = Color(0xFFF2575D)
Одной схемы не хватит для определения всех цветов. В частности, например, цвет кнопки colorRed. Вроде как он primary, но это сойство в схеме уже забито  primary = colorPrimaryDark,
Первоначально подумал создать следующее:
private val ButtonLightColorScheme = lightColorScheme(
    primary = colorRed,
)
Но вижу что нельзя наверняка расширить MaterialTheme.
Нельзя ли каким-то образом расширить эти цвета (например выделить ещё цвета для кнопок и текстов) ? Каким образом  это реализуется по правилам, чтобы брать цвета из темы ?
Ведь не заносить на какие-нибудь "свободные" из light схемы)

2023-10-23 10:02 UTC, LexaNik commented on app/favourites_screen/src/main/java/com/example/favouritesscreen/composables/FavouritesScreen.kt
> +                if ((createTagSheetViewModelState.isValid)
Этот код поменяется (в связи с новой реализацией по комментарию ниже).

2023-10-23 10:02 UTC, LexaNik commented on app/favourites_screen/src/main/java/com/example/favouritesscreen/composables/FavouritesScreen.kt
> +    Scaffold(
Этот код поменяется (в связи с новой реализацией по комментарию ниже).

2023-10-23 10:02 UTC, LexaNik commented on app/favourites_screen/src/main/java/com/example/favouritesscreen/composables/FavouritesScreen.kt
> +                val createTagSheetViewModelState = createTagSheetViewModel.getState().value
Этот код поменяется (в связи с новой реализацией по комментарию ниже).

2023-10-23 10:05 UTC, LexaNik commented
> Вообще всю логику показа боттомшита нужно переписать и разместить ее в NavigationHolder'е.
> 
> Нужно настроить "общение" между ним и экраном тегов. Делается это с помощью лямбд и эффектов. В крайнем случае можно вызывать эти экраны также, как вызывается app bar. Его вьюмодель определена прямо в NavigationHolder'е, и в него напрямую пробрасываются навигационные функции.
> 
> Мое видение решения такое - при нажатии на кнопку create на экране тегов запускать ивент, который во вьюмодели триггерит эффект. Эффект в свою очередь триггерится в LaucnhedEffect и дергает навигационный метод их Holder'а. Этот метод должен менять какое-нибудь состояние, которое хранится в функции `NavigationHolder`, чтобы вызвать декомпозицию и показать боттомшит

Переработал код по твоим советам. Надеюсь правильно всё понял)

2023-11-01 10:40 UTC, Steyrix requested changes
В общем, всё ещё есть недоработки по архитектуре и нарушение некоторых принципов инкапсуляции, но уже гораздо лучше и видно, что проделана хорошая работа ) Молодец! Исправь это, по идее не должно занять много времени

2023-11-01 10:40 UTC, Steyrix commented on app/create_tag_sheet/src/main/java/com/example/createtagsheet/CreateTagSheetViewModel.kt
> +
Лишняя пустая строка

2023-11-01 10:40 UTC, Steyrix commented on app/create_tag_sheet/src/main/java/com/example/createtagsheet/composables/CreateTagInput.kt
> +
лишняя пустая строка

2023-11-01 10:40 UTC, Steyrix commented on app/create_tag_sheet/src/main/java/com/example/createtagsheet/composables/TagCreatedLabel.kt
> +
лишняя пустая строка

2023-11-01 10:40 UTC, Steyrix commented on app/src/main/java/com/llcompany/nerdtranslator/base/main/BottomSheetViewModel.kt
> +        BottomSheetContract.Effect>() {
тут нужен отступ

2023-11-01 10:40 UTC, Steyrix commented on app/src/main/java/com/llcompany/nerdtranslator/base/main/BottomSheetViewModel.kt
> +        BottomSheetContract.Effect>() {
пустая строка то есть

2023-11-01 10:40 UTC, Steyrix commented on app/src/main/java/com/llcompany/nerdtranslator/base/main/TopAppBarViewModel.kt
> +            TopAppBarContract.Event.BackSheetActionClick -> {
Что делает этот эффект?

2023-11-01 10:40 UTC, Steyrix commented on app/src/main/java/com/llcompany/nerdtranslator/base/navigation/NavigationHolder.kt
> +    val createTagSheetViewModel = getViewModel<CreateTagSheetViewModel>()
То, что здесь инжектится эта вьюмодель - нехорошо. Нам здесь нужны только общие вьюмодели для аппбара и боттомшита

2023-11-01 10:40 UTC, Steyrix commented on app/src/main/java/com/llcompany/nerdtranslator/base/navigation/NavigationHolder.kt
> +                                    createTagSheetViewModel.setIsCreated(true)
Регулировка этого состояния должна осуществляться с помощью ивентов

2023-11-01 10:40 UTC, Steyrix commented on app/src/main/java/com/llcompany/nerdtranslator/base/navigation/NavigationHolder.kt
> +                                    createTagSheetViewModel.setIsCreated(true)
Нужно реализовать эту функцию на стороне CreateTagSheet

2023-11-05 13:35 UTC, LexaNik commented on app/src/main/java/com/llcompany/nerdtranslator/base/navigation/NavigationHolder.kt
> +    val createTagSheetViewModel = getViewModel<CreateTagSheetViewModel>()
Переделал на вызов события внутри CreateTagSheet. Убрал createTagSheetViewModel .

2023-11-05 13:36 UTC, LexaNik commented on app/src/main/java/com/llcompany/nerdtranslator/base/navigation/NavigationHolder.kt
> +                                    createTagSheetViewModel.setIsCreated(true)
Реализовал на стороне CreateTagSheet Event.

2023-11-05 13:46 UTC, LexaNik commented on app/src/main/java/com/llcompany/nerdtranslator/base/main/TopAppBarViewModel.kt
> +            TopAppBarContract.Event.BackSheetActionClick -> {
Предполагал сделать кнопку возврата (иконка) для AppBar на Favorites.
![image](https://github.com/vamelchenia/nerd-translator/assets/145274573/62417a03-ed0f-40a9-bd91-36d9d6c834aa)
Оставил пока так, потому что приоритетом стало показ bottomsheet.

2023-11-05 14:06 UTC, Steyrix requested changes
Остались косметические замечания

2023-11-05 14:06 UTC, Steyrix commented on app/create_tag_sheet/src/main/java/com/example/createtagsheet/composables/CreateTagInput.kt
> +    {
Кажется, что эта фигурная скобка должна быть на предыдущей строке

2023-11-05 14:06 UTC, Steyrix commented on app/create_tag_sheet/src/main/java/com/example/createtagsheet/composables/TagCreatedLabel.kt
> +    {
Тут то же самое с фигурной скобкой

2023-11-05 14:06 UTC, Steyrix commented on app/src/main/java/com/llcompany/nerdtranslator/base/navigation/NavigationHolder.kt
> +    val sheetState = rememberModalBottomSheetState(true)
лучше назвать bottomSheetState

2023-11-05 14:06 UTC, Steyrix commented on app/src/main/java/com/llcompany/nerdtranslator/base/navigation/NavigationHolder.kt
> +                                    bottomSheetViewModel.onEventReceived(
Зачем тут это? Ты же можешь прописать вместо этого метода `onEventSent(BottomSheetContract.Event.CreateTagActionClick)`

2023-11-05 14:06 UTC, Steyrix commented on app/src/main/java/com/llcompany/nerdtranslator/base/navigation/NavigationHolder.kt
> +                            modifier = Modifier
Этот модифаер повторяется ниже, можно вынести в переменную

2023-11-05 14:38 UTC, Steyrix commented on app/src/main/java/com/llcompany/nerdtranslator/base/navigation/NavigationHolder.kt
> +                                    bottomSheetViewModel.onEventReceived(
Ошибся, можно оставить как есть

2023-11-05 14:41 UTC, LexaNik commented on app/src/main/java/com/llcompany/nerdtranslator/base/navigation/NavigationHolder.kt
> +                                    bottomSheetViewModel.onEventReceived(
Оставил bottomSheetViewModel.onEventReceived( , т.к. onEventSent не определен.

2023-11-05 14:45 UTC, Steyrix approved these changes

2023-11-05 14:54 UTC, vamelchenia approved these changes

2023-11-05 14:54 UTC, merged