Tag screen
vamelchenia/nerd-translator pull request #21
Opened 2023-10-19 12:02 UTC by MetallFlame

Tag screen module added with tag element end edit button

2023-10-20 13:49 UTC, MetallFlame commented
![image](https://github.com/vamelchenia/nerd-translator/assets/23457253/f3e6fb1d-49e6-459a-94ff-1e09904398a9)
![image](https://github.com/vamelchenia/nerd-translator/assets/23457253/c5a2d4a6-7d3f-4920-bac2-b9e8c34a827e)

2023-10-22 19:33 UTC, Steyrix requested changes
В целом все хорошо, непонятны только файлы содержащие только превью функции. Обычно превью функции пишется рядом с её реализацией.
Лишние файлы нужно удалить. Но я пока так и не понял, какой экран ты делаешь. Скинь пожалуйста скрин из фигмы этого экрана

2023-10-22 19:33 UTC, Steyrix commented on app/tag_screen/src/androidTest/java/com/example/tag_screen/ExampleInstrumentedTest.kt
> +package com.example.tag_screen
Можно этот файл удалить

2023-10-22 19:33 UTC, Steyrix commented on app/tag_screen/src/main/java/com/example/tag_screen/TagScreenViewModel.kt
> +    }}
форматирование съехало

2023-10-22 19:33 UTC, Steyrix commented on app/tag_screen/src/main/java/com/example/tag_screen/composables/CreateButton.kt
> +private val buttonColorPrimaryNormal = Color(0xFFF2575D)
Возможно эти цвета уже есть в теме приложения. Проверь, как мы используем цвета при помощи `MaterialTheme `в других файлах

2023-10-22 19:33 UTC, Steyrix commented on app/tag_screen/src/main/java/com/example/tag_screen/composables/Tag.kt
> +fun Tag(tagName : String, tagCount : Int, active : Boolean) {
Аргументы в функциях лучше писать построчно, особенно если их много. Булевские переменные обычно именуют при помощи модальных глаголов, то есть в данном случае лучше будет смотреться `isActive`

2023-10-22 19:33 UTC, Steyrix commented on app/tag_screen/src/test/java/com/example/tag_screen/ExampleUnitTest.kt
> +package com.example.tag_screen
Тоже можно удалить

2023-10-22 19:33 UTC, Steyrix commented on app/tag_screen/src/main/java/com/example/tag_screen/composables/TagScreenImage.kt
> +
Лишняя пустая строка

2023-10-22 19:33 UTC, Steyrix commented on app/tag_screen/src/main/java/com/example/tag_screen/composables/TagScreenImage.kt
> +
Не совсем кстати понятно, зачем файл в котором единственная функция - это превью

2023-10-22 19:33 UTC, Steyrix commented on app/tag_screen/src/main/java/com/example/tag_screen/composables/TagContainer.kt
> +fun TagContainer() {
А что это за экран? Тоже тестовый? Мы их в коммиты не добавляем

2023-10-26 10:50 UTC, MetallFlame commented
![image](https://github.com/vamelchenia/nerd-translator/assets/23457253/1d24c428-4fee-41f0-a97c-93e2819a1046)
В моем таске была реализация самого тега и кнопки редактирования. На этом экране они и присутствуют, плюс еще кнопка создания тега. Я думал, что сразу смогу сделать контейнер, который в себе содержит все эти элементы, и в последующем можно будет его использовать при сборке приложения.

2023-11-01 10:19 UTC, Steyrix commented
Кнопка создания не нужна, ее делает @LexaNik. В целом, сейчас нужно оставить только экран тега и его редактирования. Остальное нужно удалить. Потом заведем таску на внедрение экрана в существующий флоу

2023-11-01 10:20 UTC, Steyrix commented
> Кнопка создания не нужна, ее делает @LexaNik. В целом, сейчас нужно оставить только экран тега и его редактирования. Остальное нужно удалить. Потом заведем таску на внедрение экрана в существующий флоу

Когда пофиксишь замечания, кликай под ними на Resolve conversation

2023-11-01 14:52 UTC, Steyrix requested changes
Need fix

2023-11-01 18:19 UTC, Steyrix approved these changes

2023-11-01 18:19 UTC, merged