Implement Create tag bottom sheet with screens: Favourites no tags, Favourites first tag and Favourites tags
vamelchenia/nerd-translator pull request #31
Opened 2023-11-26 03:04 UTC by LexaNik

TODO:
1. List tags (after it implementation in core) on Favourites first tag and Favourites tags
2. Search and Sorting on Favourites tags

![image](https://github.com/vamelchenia/nerd-translator/assets/145274573/68ae7852-a20b-4fbb-84ba-16da7c36d6a7)

2023-11-28 10:52 UTC, Steyrix commented on app/favourites_screen/build.gradle.kts
> +    implementation(project(":app:tag_screen"))
Непонятно, зачем здесь импорт другого модуля. У нас в идеале модули не должны ссылаться друг на друга, можно ссылаться только на кор модуль

2023-11-28 10:52 UTC, Steyrix commented on app/src/main/java/com/llcompany/nerdtranslator/base/navigation/FavouritesTagsScreenDestination.kt
> +fun FavouritesTagsScreenDestination(navigateToCreateTagSheet: () -> Unit) {
Мы не поняли друг друга в этом вопросе ) У тебя для этого экрана должен быть один destination, внутри которого ты в зависимости от какой-то переменной будешь решать, каким образом его открыть.

Смотри, по сути это один и тот же экран, который имеет несколько вариантов отображения в зависимости от данных в приложении. Так что для него один destination.

Другие экраны, например создание тега, имеют отдельный destination. 

Суть в том, что у тебя вьюмодель для этого экрана фактически начинает управлять несколькими дестинейшнами, что неверно.

2023-11-28 13:20 UTC, Steyrix requested changes

2023-11-28 13:20 UTC, Steyrix commented on app/favourites_screen/build.gradle.kts
> +    implementation(project(":app:tag_screen"))
.

2023-11-29 15:30 UTC, LexaNik commented on app/favourites_screen/build.gradle.kts
> +    implementation(project(":app:tag_screen"))
Жду реализации от Артема таг листа в коре. Потому это выпилится)

2023-11-29 15:33 UTC, LexaNik commented on app/src/main/java/com/llcompany/nerdtranslator/base/navigation/FavouritesTagsScreenDestination.kt
> +fun FavouritesTagsScreenDestination(navigateToCreateTagSheet: () -> Unit) {
Да, теперь понял. Переделываю как обсудили: регулировка данными из состояния, которые будут браться из репозитория. Репозиторий для сетевых запросов (точнее его первый прототип) реализован в ветке feature/networking.

2023-12-07 11:34 UTC, Steyrix requested changes

2023-12-08 21:18 UTC, LexaNik commented on app/favourites_screen/build.gradle.kts
> +    implementation(project(":app:tag_screen"))
Вынес с TODO. После мержа ПР от Артема удалю implementation.

2023-12-08 21:21 UTC, LexaNik commented on app/core/src/main/java/com/example/core/tags/TagsManagerRepository.kt
> +interface TagsManagerRepository {
Да. Скорее всего.
Добавил getTags().

2023-12-08 21:34 UTC, LexaNik commented on app/src/main/java/com/llcompany/nerdtranslator/base/main/BottomSheetViewModel.kt
> +                if (tagsRepository.createTag()) {
А как без проверки будут в дальнейшем обрабатываться ошибки создания тега. Например если тег не создался ?
Тогда ведь нам нет необходимости по идее переходить на страницу созданного тега...Лишь для этих целей была создана проверка...
Пока убрал) Понимаю что каким-то другим образом всё это будет обрабатываться.

2023-12-08 23:07 UTC, LexaNik commented on app/favourites_screen/src/main/java/com/example/favouritesscreen/composables/FavouritesScreen.kt
>      when (state.tagCount) {
Создал Enum.

2023-12-10 14:45 UTC, Steyrix commented on app/core/src/main/java/com/example/core/tags/TagsManagerRepositoryImpl.kt
> +        preferencesManager = PreferencesManager(context)
Это неправильно. Пусть лучше Koin создаст менеджер, который ты сразу заинжектишь в этот репозиторий. И не придется контекст здесь держать тогда )

2023-12-10 14:45 UTC, Steyrix commented on app/create_tag_sheet/src/main/java/com/example/createtagsheet/CreateTagSheetContract.kt
> +        data class CreateButtonActionClick(
А что за ивент такой? Почему у него нуллабельный параметр?

2023-12-10 14:45 UTC, Steyrix commented on app/favourites_screen/src/main/java/com/example/favouritesscreen/FavouritesScreenViewModel.kt
> +                    val areTagsExisting by mutableStateOf(tagsRepository.areTagsExisting())
Это не совсем правильно. Непонятно зачем здесь метательные скейты. Это же вьюмодель. Смысл обозревать метательные стейты есть на уровне композабл функций, тут это не нужно

2023-12-10 14:45 UTC, Steyrix commented on app/favourites_screen/src/main/java/com/example/favouritesscreen/composables/FavouritesScreen.kt
> +    LaunchedEffect(Unit) {
Тоже неправильно. При каждой рекомпозиции будет этот ивент вызываться

2023-12-10 14:45 UTC, Steyrix commented on app/favourites_screen/src/main/java/com/example/favouritesscreen/composables/FavouritesScreen.kt
> +    LaunchedEffect(Unit) {
Мне в целом неясно, зачем ты вручную здесь вызываешь рефреш

2023-12-10 14:45 UTC, Steyrix commented on app/favourites_screen/src/main/java/com/example/favouritesscreen/composables/FavouritesScreen.kt
>      when (state.tagsState) {
Попробуй подписаться тут на `state.tagsState` следующим образом

`var tagsState by remember { mutableStateOf (state.tagsState) },` возможно это поможет подтягивать обновления стейта

2023-12-10 14:45 UTC, Steyrix commented on app/favourites_screen/src/main/java/com/example/favouritesscreen/composables/FavouritesScreen.kt
> +    LaunchedEffect(Unit) {
Похоже ты как раз и хотел, чтобы при каждой рекомпозиции обновлялся Стейт. Но это сайд-эффект, что делает поведение этой функции немного непредсказуемым.

2023-12-10 16:00 UTC, LexaNik commented on app/core/src/main/java/com/example/core/tags/TagsManagerRepositoryImpl.kt
> +        preferencesManager = PreferencesManager(context)
Согласен) Изменил этот код и код в TagsManagerModule.kt

2023-12-10 16:21 UTC, LexaNik commented on app/create_tag_sheet/src/main/java/com/example/createtagsheet/CreateTagSheetContract.kt
> +        data class CreateButtonActionClick(
Ивент по кнопке создания тега modalbottomsheet. Передаю название создаваемого тега. Нуллабельность убрал. 

 is CreateTagSheetContract.Event.CreateButtonActionClick -> {
                tagsRepository.createTag(event.tagName)
                applyEffect {
                    CreateTagSheetContract.Effect.Navigation.CreateTag
                }
...

2023-12-10 16:28 UTC, LexaNik commented on app/favourites_screen/src/main/java/com/example/favouritesscreen/composables/FavouritesScreen.kt
> +    LaunchedEffect(Unit) {
Дело в том, что без этого сайд-эффекта не обновляется состояние. Может конечно не совсем правильно архитектуру продумал, но не меняется state, хотя во вьюмодели значение меняется.

2023-12-10 16:28 UTC, LexaNik commented on app/favourites_screen/src/main/java/com/example/favouritesscreen/composables/FavouritesScreen.kt
>      when (state.tagsState) {
Пробовал таким образом - всё равно state.tagsState не рефрешится, хотя во вьюмодели он и обновляется. Непонятно)

2023-12-10 16:32 UTC, LexaNik commented on app/favourites_screen/src/main/java/com/example/favouritesscreen/FavouritesScreenViewModel.kt
> +                    val areTagsExisting by mutableStateOf(tagsRepository.areTagsExisting())
Только таким образом получилось рефрешить state. Ниже в комментариях пояснения. Может поможешь с этим моментом ? Подскажешь что попробовать можно ещё ?

2023-12-10 16:34 UTC, LexaNik commented on app/favourites_screen/src/main/java/com/example/favouritesscreen/FavouritesScreenViewModel.kt
> +                    val areTagsExisting by mutableStateOf(tagsRepository.areTagsExisting())
https://github.com/vamelchenia/nerd-translator/assets/145274573/e221e5dc-c6c4-4f11-96c8-26bd6c6440da

2023-12-12 16:00 UTC, merged