Tag list
vamelchenia/nerd-translator pull request #32
Opened 2023-12-01 10:52 UTC by MetallFlame

Add TagList function to display a list of tags

2023-12-07 11:38 UTC, Steyrix requested changes

2023-12-07 11:38 UTC, Steyrix commented on app/core/src/main/java/com/example/core/ui/composables/TagList.kt
> +private val containerMargins = PaddingValues(9.dp, 0.dp, 10.dp, 72.dp)
Должна быть пустая строка после этой переменной

2023-12-14 12:19 UTC, Steyrix approved these changes

2023-12-14 17:24 UTC, vamelchenia approved these changes

2023-12-14 17:24 UTC, merged